version: '3.8'

services:
  # Service PHP
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # Service Nginx
  web:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  # Service de base de données (MySQL par exemple)
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

volumes:
  dbdata: