version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel-network
  php1:
    build:
      context: ./TP-Final-3IW-ESGI
      dockerfile: Dockerfile
    user: www-data
    volumes:
      - ./TP-Final-3IW-ESGI:/var/www/html
      - laravel-vendor1:/var/www/html/vendor
    networks:
      - laravel-network
    depends_on:
      - db

  php2:
    build:
      context: ./TP-Final-3IW-ESGI2
      dockerfile: Dockerfile
    user: www-data
    volumes:
      - ./TP-Final-3IW-ESGI2:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  nginx1:
    image: nginx:latest
    volumes:
      - ./TP-Final-3IW-ESGI/nginx.conf:/etc/nginx/conf.d/default.conf
      - laravel-vendor2:/var/www/html/vendor
    ports:
      - "8080:80"
    networks:
      - laravel-network
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    volumes:
      - ./TP-Final-3IW-ESGI2/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - laravel-network
    depends_on:
      - php2

networks:
  laravel-network:
volumes:
  laravel-vendor1:
  laravel-vendor2:
