# Utilisation de l'image officielle Nginx comme base
FROM nginx:alpine

# Supprimer la configuration Nginx par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier la configuration Nginx personnalisée dans le conteneur
COPY nginx.conf /etc/nginx/conf.d

# Exposer le port 80
EXPOSE 80

# Démarrer Nginx en mode foreground
CMD ["nginx", "-g", "daemon off;"]